# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Women Who Go Delhi 
email: delhi@womenwhogo.org # Mailing list
description: > # this means to ignore newlines until "baseurl:"
  You do not need to know Go, be a professional developer or enjoy talking to strangers in order to come hang out with us!
  This group is for you if you are interested in Go, and are looking for a safe space to learn.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social
githubUsername: wwgdelhi
twitterUsername: womenwhogo_del

# Build settings
markdown: kramdown

themeColor: blue # green, purple, orange, blue, grey
fixedNav: 'true' # true or false

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
